import { getDocumentProxy, extractText } from "unpdf";

/**
 * Extracts lease fields from a PDF generated by the specific PandaDoc
 * "Single-Room Rental Agreement" (TX) template this landlord reuses for
 * every room lease. PandaDoc flattens filled values into the page content
 * stream (no AcroForm fields survive), so there is no field-name metadata
 * to read — values are matched to their label by (x, y) proximity within
 * the same template. This is inherently template-shaped: it works because
 * every export of *this* template keeps the same labels at the same
 * relative position, not because it understands leases in general.
 */

export type ParsedLease = {
  landlordName?: string;
  tenantName?: string;
  tenantEmail?: string;
  propertyAddress?: string;
  unitIdentifier?: string;
  leaseStart?: string; // YYYY-MM-DD
  termMonths?: number;
  leaseEnd?: string; // YYYY-MM-DD, computed from leaseStart + termMonths
  rentAmount?: string; // plain dollars, e.g. "650"
  lateFee?: string;
  securityDeposit?: string;
  paymentMethods?: string;
  payableTo?: string;
  utilitiesExceptions?: string;
  overnightGuestNights?: string;
  substancePolicy?: string;
  parkingRules?: string;
  documentRef?: string;
  completedAt?: string;
  notes: string;
  warnings: string[];
};

export type Item = { str: string; x: number; y: number; font: string };

const LINE_HEIGHT = 11;
const ROW_TOLERANCE = 6;

// Static template text (labels, headings, bullet markers) in this template's
// PDF export always lands on font resources g_d0_f1 or g_d0_f3 — the first
// two distinct fonts pdf.js encounters on a page — while every filled-in
// value uses a later one (f5/f8/f10/f12/f13 depending on field type).
// Concretely, this is *why* a label like "Tenant (Full Legal Name):" comes
// back as multiple items instead of one ("Tenant (Full Legal" / "N" /
// "ame):"): pdf.js occasionally switches font mid-label for a single glyph
// run (e.g. around a capital letter), and that switch still lands on f1/f3,
// so it stays "static text" rather than leaking into a value. Filtering
// candidates to "not font f1/f3" is what cleanly separates static template
// text sharing a row with a value from the value itself. This is a property
// of pdf.js's font-loading order for *this* PDF, re-verified against a real
// export rather than assumed — a different PDF generator (or a future
// pdf.js version) is not guaranteed to number fonts the same way, so this
// constant should be re-derived (dump page.getTextContent() items with
// coordinates + fontName) if this template ever changes.
const STATIC_TEMPLATE_FONTS = new Set(["g_d0_f1", "g_d0_f3"]);

export function isBlank(str: string): boolean {
  const s = str.trim();
  return s === "" || /^[_•]+\.?$/.test(s);
}

async function pageItems(
  pdf: Awaited<ReturnType<typeof getDocumentProxy>>,
  pageNumber: number,
): Promise<Item[]> {
  const page = await pdf.getPage(pageNumber);
  const content = await page.getTextContent();
  return content.items
    .filter(
      (
        it,
      ): it is typeof it & {
        str: string;
        transform: number[];
        fontName: string;
      } => "transform" in it,
    )
    .map((it) => ({
      str: it.str,
      x: it.transform[4],
      y: it.transform[5],
      font: it.fontName,
    }));
}

/** Finds the item containing `labelSubstring`, then returns the nearest
 * other (non-blank, non-label) item on the same visual line — optionally
 * offset by whole lines, for values that wrap onto the line below their
 * label rather than sitting beside it. */
export function valueNearLabel(
  items: Item[],
  labelSubstring: string,
  opts: { offsetLines?: number } = {},
): string | undefined {
  const labelIndex = items.findIndex((it) => it.str.includes(labelSubstring));
  if (labelIndex === -1) return undefined;
  const label = items[labelIndex];
  const targetY = label.y - (opts.offsetLines ?? 0) * LINE_HEIGHT;

  const candidates = items.filter(
    (it, i) =>
      i !== labelIndex &&
      Math.abs(it.y - targetY) <= ROW_TOLERANCE &&
      !isBlank(it.str) &&
      !STATIC_TEMPLATE_FONTS.has(it.font),
  );
  if (candidates.length === 0) return undefined;
  candidates.sort((a, b) => a.x - b.x);
  return candidates
    .map((c) => c.str.trim())
    .join(" ")
    .trim();
}

export function stripMoney(value: string | undefined): string | undefined {
  if (!value) return undefined;
  const n = value.replace(/[^0-9.]/g, "");
  return n === "" ? undefined : n;
}

export function normalizeNameTokens(name: string): Set<string> {
  return new Set(
    name
      .toUpperCase()
      .replace(/[^A-Z\s]/g, "")
      .split(/\s+/)
      .filter(Boolean),
  );
}

export type Signer = { name: string; email: string };

export function parseSigners(certificateText: string): Signer[] {
  const signers: Signer[] = [];
  const re = /\n([A-Z][A-Z .'-]{2,60})\nEMAIL\n([^\s]+@[^\s]+)\n/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(certificateText))) {
    signers.push({ name: m[1].trim(), email: m[2].trim() });
  }
  return signers;
}

export function pickTenantEmail(
  signers: Signer[],
  tenantName: string | undefined,
): string | undefined {
  if (signers.length === 0) return undefined;
  if (!tenantName) return undefined;
  const tenantTokens = normalizeNameTokens(tenantName);
  let best: Signer | undefined;
  let bestScore = 0;
  for (const signer of signers) {
    const tokens = normalizeNameTokens(signer.name);
    let score = 0;
    for (const t of tokens) if (tenantTokens.has(t)) score++;
    if (score > bestScore) {
      bestScore = score;
      best = signer;
    }
  }
  return bestScore > 0 ? best?.email : undefined;
}

/** start + months, clamped to the last day of the resulting month (e.g. Aug
 * 31 + 6mo -> Feb 28, not an overflowed March date). */
export function addMonthsClamped(startISO: string, months: number): string {
  const [y, m, d] = startISO.split("-").map(Number);
  const totalMonths = m - 1 + months;
  const targetYear = y + Math.floor(totalMonths / 12);
  const targetMonth = ((totalMonths % 12) + 12) % 12; // 0-indexed
  const lastDayOfTargetMonth = new Date(
    Date.UTC(targetYear, targetMonth + 1, 0),
  ).getUTCDate();
  const day = Math.min(d, lastDayOfTargetMonth);
  const end = new Date(Date.UTC(targetYear, targetMonth, day));
  return end.toISOString().slice(0, 10);
}

export function buildNotes(fields: ParsedLease): string {
  const lines: string[] = [];
  if (fields.securityDeposit)
    lines.push(`Security deposit: $${fields.securityDeposit}`);
  if (fields.lateFee) lines.push(`Late fee: $${fields.lateFee}`);
  if (fields.paymentMethods)
    lines.push(`Accepted payment: ${fields.paymentMethods}`);
  if (fields.payableTo) lines.push(`Payable to: ${fields.payableTo}`);
  if (fields.overnightGuestNights)
    lines.push(
      `Overnight guests: ${fields.overnightGuestNights} consecutive nights/mo max`,
    );
  if (fields.utilitiesExceptions)
    lines.push(`Utility exceptions: ${fields.utilitiesExceptions}`);
  if (fields.substancePolicy)
    lines.push(`Alcohol/substance policy: ${fields.substancePolicy}`);
  if (fields.parkingRules) lines.push(`Parking: ${fields.parkingRules}`);
  if (fields.propertyAddress)
    lines.push(`PDF property address: ${fields.propertyAddress}`);
  if (fields.documentRef) lines.push(`PandaDoc ref: ${fields.documentRef}`);
  if (fields.completedAt)
    lines.push(`Signed by all parties: ${fields.completedAt}`);
  return lines.join("\n");
}

export async function parseLeasePdf(bytes: Uint8Array): Promise<ParsedLease> {
  // pdf.js detaches `bytes`' backing ArrayBuffer as a side effect of
  // parsing (transfers ownership rather than copying) — after this call,
  // `bytes.byteLength` is 0. Harmless for parseLeaseFile/importLease today
  // since each is a separate Server Action call that reads a fresh
  // ArrayBuffer from the uploaded File, but don't reuse `bytes` here for
  // anything else (e.g. re-uploading the original PDF) without re-reading.
  //
  // verbosity: ERRORS-only silences two pdfjs warnings that are harmless
  // here (confirmed by identical, correct extraction with and without
  // them) and just noise for a text-only, non-rendering use of pdfjs:
  //  - "Math.sumPrecise is not a function": pdfjs feature-detects a
  //    still-experimental V8 API for precise float summation and falls
  //    back to regular summation when it's absent from the Node runtime.
  //  - "Cannot substitute the font because of its name: ...": pdfjs tries
  //    to load a local system-font substitute for glyph-metrics purposes;
  //    Node has no system fonts to substitute with, but text extraction
  //    reads glyph data from the PDF's own embedded font program, not the
  //    substitute, so this doesn't affect the extracted text.
  // Real errors (a corrupt/unreadable PDF) still surface — ERRORS is the
  // most severe pdfjs verbosity level, not "silent".
  const pdf = await getDocumentProxy(bytes, { verbosity: 0 });
  const warnings: string[] = [];

  const page1 = await pageItems(pdf, 1);
  const landlordName = valueNearLabel(page1, "Landlord/Owner:");
  const tenantName = valueNearLabel(page1, "Tenant (Full Legal");
  const propertyAddress = valueNearLabel(page1, "Property Address:");
  const unitIdentifier = valueNearLabel(page1, "Private Room:");
  const leaseStart = valueNearLabel(page1, "Lease Start Date:");
  const termMonthsRaw = valueNearLabel(page1, "Initial Term Length (months):");
  const rentAmount = stripMoney(valueNearLabel(page1, "Monthly Rent Amount:"));
  const lateFee = stripMoney(valueNearLabel(page1, "A late fee of $"));
  const paymentMethods = valueNearLabel(page1, "Accepted payment methods:");
  const payableTo = valueNearLabel(page1, "Accepted payment methods:", {
    offsetLines: 1,
  });
  const securityDeposit = stripMoney(
    valueNearLabel(page1, "Security Deposit Amount:"),
  );

  for (const [label, value] of [
    ["Landlord/Owner", landlordName],
    ["Tenant name", tenantName],
    ["Property address", propertyAddress],
    ["Private room", unitIdentifier],
    ["Lease start date", leaseStart],
    ["Monthly rent", rentAmount],
  ] as const) {
    if (!value) warnings.push(`Could not find "${label}" — check manually.`);
  }

  const termMonths = termMonthsRaw ? Number(termMonthsRaw) : undefined;
  const leaseEnd =
    leaseStart && termMonths
      ? addMonthsClamped(leaseStart, termMonths)
      : undefined;

  const page2 = await pageItems(pdf, 2);
  const utilitiesExceptions = valueNearLabel(
    page2,
    "Exceptions / Additional Charges:",
  );
  const overnightGuestNights = valueNearLabel(
    page2,
    "Overnight guests are limited to",
  );
  const substancePolicy = valueNearLabel(
    page2,
    "Property-wide alcohol/substance policy",
  );

  const page6 = await pageItems(pdf, 6);
  const parkingRules = valueNearLabel(
    page6,
    "Assigned parking spot(s) / street parking rules:",
  );

  const { text } = await extractText(pdf, { mergePages: false });
  const lastPageText = text[text.length - 1] ?? "";
  const documentRef = lastPageText.match(/REF\. NUMBER\n([A-Z0-9-]+)/)?.[1];
  const completedAt = lastPageText.match(
    /DOCUMENT COMPLETED BY ALL PARTIES ON\n([^\n]+)/,
  )?.[1];
  const signers = parseSigners(lastPageText);
  const tenantEmail = pickTenantEmail(signers, tenantName);
  if (signers.length > 0 && !tenantEmail) {
    warnings.push("Could not identify tenant's email among signers.");
  }

  const fields: ParsedLease = {
    landlordName,
    tenantName,
    tenantEmail,
    propertyAddress,
    unitIdentifier,
    leaseStart,
    termMonths,
    leaseEnd,
    rentAmount,
    lateFee,
    securityDeposit,
    paymentMethods,
    payableTo,
    utilitiesExceptions,
    overnightGuestNights,
    substancePolicy,
    parkingRules,
    documentRef,
    completedAt,
    notes: "",
    warnings,
  };
  fields.notes = buildNotes(fields);
  return fields;
}
